export const TYPES = {
  Logger: Symbol.for('Logger'),
  DbPool: Symbol.for('DbPool'),
  RedisClient: Symbol.for('RedisClient'),
  IUserRepository: Symbol.for('IUserRepository'),
  IUserCredentialRepository: Symbol.for('IUserCredentialRepository'),
  IUserSessionRepository: Symbol.for('IUserSessionRepository'),
  IRefreshTokenRepository: Symbol.for('IRefreshTokenRepository'),
  ITokenService: Symbol.for('ITokenService'),
  ISessionStore: Symbol.for('ISessionStore'),
  IAuthAuditService: Symbol.for('IAuthAuditService'),
  IAuthUnitOfWork: Symbol.for('IAuthUnitOfWork'),
  ISecurityThrottleService: Symbol.for('ISecurityThrottleService'),
  HealthController: Symbol.for('HealthController'),
  AuthController: Symbol.for('AuthController'),
  LoginUseCase: Symbol.for('LoginUseCase'),
  RegisterUseCase: Symbol.for('RegisterUseCase'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  LogoutUseCase: Symbol.for('LogoutUseCase'),
  LogoutAllUseCase: Symbol.for('LogoutAllUseCase'),
  ChangePasswordUseCase: Symbol.for('ChangePasswordUseCase'),
} as const
