sonar.projectKey=auth-backend
sonar.projectName=auth-backend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.exclusions=dist/**,coverage/**,drizzle/**,node_modules/**
sonar.coverage.exclusions=**/*.d.ts,src/main/**,src/config/**,src/types/**,src/infrastructure/db/migrations/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
