export const LOGIN_FAILURE_WINDOW_SECONDS = 15 * 60
export const ACCOUNT_LOCK_THRESHOLD = 5
export const IP_LOCK_THRESHOLD = 10
export const PASSWORD_SPRAY_DISTINCT_ACCOUNT_THRESHOLD = 5
export const LOCK_BASE_SECONDS = 60
export const LOCK_MAX_SECONDS = 15 * 60
